platform :ios, '10.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/vtmaps/pod_control.git'
source 'https://cdn.cocoapods.org/'

target 'RNVTMapGLExample' do

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({'Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1'})

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
      end
      target.build_configurations.each do |config|
       if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 10.0
         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
       end 
     end
     if target.name == "React"
      target.remove_from_project
     end
    end
  end

  # for use_frameworks!
  # pod 'react-native-vtmap-gl/DynamicLibrary', :path => '../../'
  # use_frameworks!

  target 'RNVTMapGLExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RNVTMapGLExample-tvOS' do
  # Pods for RNVTMapGLExample-tvOS

  target 'RNVTMapGLExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
